# Generated by Django 3.1.7 on 2021-10-04 14:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatyouwant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('product_want', models.EmailField(max_length=260)),
                ('full_name', models.EmailField(max_length=70)),
                ('company_name', models.EmailField(max_length=120)),
                ('phone_number', models.EmailField(max_length=30)),
                ('type', models.EmailField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True)),
                ('mobile', models.CharField(default='123456789', max_length=120)),
                ('img', models.ImageField(default='profile1.png', upload_to='pics', verbose_name='Profile Image')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('aboutus', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('zip', models.CharField(blank=True, max_length=30, null=True)),
                ('organization', models.CharField(blank=True, max_length=230, null=True)),
                ('type', models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('company', 'Trading Company'), ('buying Office', 'Buying Office'), ('agent', 'Agent'), ('distributor/Wholesaler', 'Distributor/Wholesaler'), ('government', 'Government ministry/Bureau/Commission'), ('association', 'Association'), ('business', 'Business Service (Transportation, finance, travel, Ads, etc)'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Verified'), (1, 'Unverified'), (2, 'Hold')], default=0)),
                ('img1', models.ImageField(default='static/vivah/img/profile.jpg', upload_to='pics', verbose_name='Profile Image')),
                ('img2', models.ImageField(default='static/vivah/img/profile.jpg', upload_to='pics', verbose_name='Profile Image')),
                ('img3', models.ImageField(default='static/vivah/img/profile.jpg', upload_to='pics', verbose_name='Profile Image')),
                ('img4', models.ImageField(default='static/vivah/img/profile.jpg', upload_to='pics', verbose_name='Profile Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColdCoffe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
