# Generated by Django 3.1.7 on 2021-10-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldcoffe',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='whatyouwant',
            options={'managed': False},
        ),
    ]
