# Generated by Django 3.1.7 on 2021-10-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211011_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
    ]
