# Generated by Django 3.1.7 on 2021-10-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211011_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilefo',
            field=models.CharField(blank=True, choices=[('Myself', 'Myself'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Relative', 'Relative'), ('Friend', 'Friend')], max_length=20, null=True),
        ),
    ]
