# Generated by Django 3.1.7 on 2021-10-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211012_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyvalues',
            name='annualincome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='disability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='employed',
            field=models.CharField(blank=True, choices=[('Self Employed', 'Self Employed'), ('Business', 'Business'), ('Government', 'Government'), ('PSU', 'PSU'), ('MNC', 'MNC'), ('Defence', 'Defence'), ('Private', 'Private'), ('Not Working', 'Not Working')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='familystatus',
            field=models.CharField(blank=True, choices=[('Middle Class', 'Middle Class'), ('Upper Middle Class', 'Upper Middle Class'), ('Rich', 'Rich'), ('Elite', 'Elite')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='familytype',
            field=models.CharField(blank=True, choices=[('Nuclear', 'Nuclear'), ('Joint', 'Joint')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='familyvalues',
            field=models.CharField(blank=True, choices=[('Orthodox', 'Orthodox'), ('Tradational', 'Tradational'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='height',
            field=models.CharField(blank=True, choices=[('4-6', '4ft 6in / 137 cms'), ('4-7', '4ft 7in / 139 cms'), ('4-8', '4ft 8in / 142 cms'), ('4-9', '4ft 9in / 144 cms'), ('4-10', '4ft 10in / 147 cms'), ('4-11', '4ft 11in / 149 cms'), ('5', '5ft / 152 cms'), ('5-1', '5ft 1in / 154 cms'), ('5-2', '5ft 2in / 157 cms'), ('5-3', '5ft 3in / 160 cms'), ('5-4', '5ft 4in / 162 cms'), ('5-5', '5ft 5in / 165 cms'), ('5-6', '5ft 6in / 167 cms'), ('5-7', '5ft 7in / 170 cms'), ('5-8', '5ft 8in / 172 cms'), ('5-9', '5ft 9in / 175 cms'), ('5-10', '5ft 10in / 177cms'), ('5-11', '5ft 11in / 180 cms'), ('6', '6ft / 182 cms'), ('6-1', '6ft 1 in / 185 cms'), ('6-2', '6ft 2in / 187 cms'), ('6-3', '6ft 3in / 190 cms'), ('6-4', '6ft 4in / 193 cms'), ('6-5', '6ft 5in / 195 cms'), ('6-6', '6ft 6in / 198 cms')], max_length=100, null=True),
        ),
    ]
