# Generated by Django 3.1.7 on 2021-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211004_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
