# Generated by Django 3.1.7 on 2021-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211004_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='martialstatus',
            field=models.CharField(default='Single', max_length=20),
        ),
    ]
