# Generated by Django 3.1.7 on 2021-10-12 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211012_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyvalues',
            name='aboutfamily',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyvalues',
            name='brother',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familyvalues',
            name='father',
            field=models.CharField(blank=True, choices=[('Self Employed', 'Self Employed'), ('Business', 'Business'), ('Government', 'Government'), ('PSU', 'PSU'), ('MNC', 'MNC'), ('Defence', 'Defence'), ('Private', 'Private'), ('Civil Services', 'Civil Services'), ('Not Working', 'Not Working')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familyvalues',
            name='mother',
            field=models.CharField(blank=True, choices=[('Self Employed', 'Self Employed'), ('Business', 'Business'), ('Government', 'Government'), ('PSU', 'PSU'), ('MNC', 'MNC'), ('Defence', 'Defence'), ('Private', 'Private'), ('Civil Services', 'Civil Services'), ('Not Working', 'Not Working')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familyvalues',
            name='sister',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='annualincome',
            field=models.CharField(blank=True, choices=[('0', 'Rs. 0 - 1 LAKH'), ('1', 'Rs. 1 - 2 LAKH'), ('2', 'Rs. 2 - 3 LAKH'), ('3', 'Rs. 3 - 4 LAKH'), ('4', 'Rs. 4 - 5 LAKH'), ('5', 'Rs. 5 - 10 LAKH'), ('6', 'Rs. 10 - 20 LAKH'), ('7', 'Rs. 20 - 30 LAKH'), ('8', 'Rs. 30 - 40 LAKH'), ('9', 'Rs. 40 - 50 LAKH'), ('10', 'Rs. 50 - 70 LAKH'), ('11', 'Rs. 70 - 1 Core'), ('12', 'Rs. 1 core & above')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familyvalues',
            name='employed',
            field=models.CharField(blank=True, choices=[('Self Employed', 'Self Employed'), ('Business', 'Business'), ('Government', 'Government'), ('PSU', 'PSU'), ('MNC', 'MNC'), ('Defence', 'Defence'), ('Private', 'Private'), ('Civil Services', 'Civil Services'), ('Not Working', 'Not Working')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='pmartialstatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('waiting for divorced', 'Waiting For Divorced'), ('widowed', 'Widowed'), ('any status', 'Any Status'), ('never married', 'Never Married'), ('annulled', 'Annulled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='martialstatus',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('waiting for divorced', 'Waiting For Divorced'), ('widowed', 'Widowed'), ('any status', 'Any Status'), ('never married', 'Never Married'), ('annulled', 'Annulled')], default='Single', max_length=20),
        ),
    ]
