# Generated by Django 3.1.7 on 2021-10-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211012_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='horo',
            field=models.CharField(choices=[('Must', 'Must'), ('Not Necessary', 'Not Necessary')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='manglik',
            field=models.CharField(choices=[('Manglik', 'Manglik'), ('Non-manglik', 'Non-manglik'), ('Ashik manglik', 'Ashik manglik')], default=0, max_length=20),
        ),
    ]
