# Generated by Django 3.1.7 on 2021-10-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211012_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Occasionally NonVeg', 'Occasionally NonVeg'), ('Eggetarian', 'Eggetarian'), ('Jain', 'Jain'), ('Vegan', 'Vegan')], default=0, max_length=20),
        ),
    ]
