# Generated by Django 3.1.7 on 2021-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211008_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile.jpg', upload_to='pics', verbose_name='static/pic/img/profile.jpg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='videofile',
            field=models.FileField(default='videos/Krishna.mp4', null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
