# Generated by Django 3.1.7 on 2021-10-09 06:03

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211009_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
            preserve_default=False,
        ),
    ]
