# Generated by Django 3.1.7 on 2021-10-15 23:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyvalues',
            name='awards',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Occasionally NonVeg', 'Occasionally NonVeg'), ('Eggetarian', 'Eggetarian'), ('Jain', 'Jain'), ('Vegan', 'Vegan')], default='Veg', max_length=20),
        ),
    ]
