# Generated by Django 3.1.7 on 2021-10-16 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20211016_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'YES'), (2, 'SOMETIMES')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
