# Generated by Django 3.1.7 on 2021-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211021_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default=30, max_length=20),
        ),
    ]
