# Generated by Django 3.1.7 on 2021-10-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eventday',
            field=models.CharField(default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='session',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
