# Generated by Django 3.1.7 on 2021-10-31 08:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211024_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='manglik',
            field=models.CharField(choices=[('Manglik', 'Manglik'), ('Non-manglik', 'Non-manglik'), ('Ashik manglik', 'Ashik manglik')], default='Non-manglik', max_length=20),
        ),
        migrations.CreateModel(
            name='ProdComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('mobile', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodcomment', to='accounts.profile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
