# Generated by Django 3.1.7 on 2021-10-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_prodcomment_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('userrequest', models.IntegerField(default=0)),
                ('userview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userview', to='accounts.profile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
