# Generated by Django 3.1.7 on 2021-10-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_viewcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcomment',
            options={},
        ),
    ]
