# Generated by Django 3.1.7 on 2021-10-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20211031_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcomment',
            name='profile',
        ),
    ]
