# Generated by Django 3.1.7 on 2021-10-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_viewcomment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcomment',
            name='userview',
            field=models.IntegerField(default=0),
        ),
    ]
