# Generated by Django 3.1.7 on 2021-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20211031_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcomment',
            name='userview',
            field=models.IntegerField(default=0),
        ),
    ]
