# Generated by Django 3.1.7 on 2021-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20211108_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
