# Generated by Django 3.1.7 on 2021-11-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
