# Generated by Django 3.1.7 on 2021-11-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='thread',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
