# Generated by Django 3.1.7 on 2021-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20211112_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='thread',
            field=models.IntegerField(null=True),
        ),
    ]
