# Generated by Django 3.1.7 on 2021-11-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20211112_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='user_has_seen',
        ),
    ]
