# Generated by Django 3.1.7 on 2021-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mobile',
            field=models.CharField(default='123456789', max_length=120),
        ),
    ]
