# Generated by Django 3.1.7 on 2021-11-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_auto_20211108_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
