# Generated by Django 3.1.7 on 2021-11-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_auto_20211108_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
    ]
