# Generated by Django 3.1.7 on 2021-11-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0006_remove_notification_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
